### ISSUE TITLE
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (27, 2) + inhomogeneous part.

### ISSUE THREAD

**Issue by 18296545198** [clovaai/lffont#34] opened 2023-03-04 09:05 UTC

**Comment by 18296545198** [comment] 2023-03-04 09:08
Original Traceback (most recent call last):
  File "/home/zeng/.conda/envs/xky/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zeng/.conda/envs/xky/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zeng/.conda/envs/xky/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zeng/xky1/lffont-master/datasets/p1dataset.py", line 113, in __getitem__
    trg_unis, trg_comp_ids = self.check_and_sample(trg_unis, trg_comp_ids)
  File "/home/zeng/xky1/lffont-master/datasets/p1dataset.py", line 97, in check_and_sample
    uni_comps = sample(uni_comps, self.n_sample_max)
  File "/home/zeng/xky1/lffont-master/datasets/datautils.py", line 45, in sample
    population = np.asarray(list(population))
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (23, 2) + inhomogeneous part.

**Comment by 8uos** [comment] 2023-04-17 11:22
Hi, I guess that the error is caused by mismatching python/numpy version. 
It can solved by adding `dtype="object"` to line 45 of `datautils.py`.
Modifying `population = np.asarray(list(population))` to `population = np.asarray(list(population), dtype="object)` will help you.

**Comment by 18296545198** [comment] 2023-04-17 11:36
I get the picture. Thank you

**Comment by SanghyukChun** [comment] 2023-06-14 01:59
Closing the issue, assuming the answer resolves the problem.
Please re-open the issue as necessary.

**Closed by SanghyukChun** 2023-06-14 01:59 UTC
