### ISSUE TITLE
about  phase 1 training

### ISSUE THREAD

**Issue by sirius1114** [clovaai/lffont#39] opened 2023-07-28 20:29 UTC
when i ran train.py(phase 1),i got problem is  "env_get = lambda env, x, y, transform: transform(read_data_from_lmdb(env, f'{x}_{y}')['img'])         TypeError: 'NoneType' object is not subscriptable" .then i found that the return vaule “data” is None in function "read_data_from"
Looking forward to your help！
<img width="596" alt="error" src="https://github.com/clovaai/lffont/assets/130277767/4a8303f1-12ac-45dd-b478-92f00956d5cd">

<img width="264" alt="function" src="https://github.com/clovaai/lffont/assets/130277767/8595c1d9-294d-4ab2-8553-c72acc8c3f77">

**Comment by awei669** [comment] 2023-08-07 03:55
This situation shows that some data in the lmdb database is missing. It may be caused by the lack of certain writing characters in a certain style of font in your collected data set. Carefully check your problems when generating the lmdb data set.

**Comment by SanghyukChun** [comment] 2023-11-21 04:04
Thanks @awei669 ! The issue seems resolved, therefore closing the issue.

**Closed by SanghyukChun** 2023-11-21 04:04 UTC
