### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by zi1zi** [clovaai/lffont#36] opened 2023-04-17 06:58 UTC
您好，我大致看了一下您的论文，对于数据集部分有些疑问，需要您对seen fonts，unseen fonts，seen characters，unseen characters进行一下解释。尤其是unseen fonts，训练中没有出现的字体种类，测试时可以生成该种类字体吗

**Comment by SanghyukChun** [comment] 2023-04-17 07:13
Please re-write the issue in English.
If your question is related to the seen/unseen fonts/characters, please read the paper Section 4.1, or other issues such as https://github.com/clovaai/lffont/issues/1

I close the issue because the issue is in an invalid format (not English). Please check again our paper or other issues. If you have still a question, please re-open or re-write an issue in the right format.

**Closed by SanghyukChun** 2023-04-17 07:13 UTC
